version: "3.9"

services:
  redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: redis_boot
      hostname: redis_boot
      restart: unless-stopped
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
  postgres:
    container_name: bae_nono_test_postgres
    image: postgres:13-alpine
    environment:
      TZ: Asia/Seoul
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - test-db-data:/var/lib/postgresql/data
      # - ./db/initdb.d:/docker-entrypoint-initdb.d:ro

volumes:
  test-db-data: